export const Provinces = [
  "Phnom Penh",
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chnang",
  "Kampong Speu",
  "Kampong Thom",
  "kampot",
  "Kandal",
  "Koh Kong",
  "Kratié",
  "Mondulkiri",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Ratanak Kiri",
  "Siem Reap",
  "Preah Sihanouk",
  "Stung Treng",
  "Svay Rieng",
  "Takéo",
  "Oddar Meanchey",
  "Kep",
  "Pailin",
  "Tboung Khmum",
];
